name: Release Drafter

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: .github/release-drafter-config.yml
